package com.linfeiyang.shop.mybatis.model;

import java.io.Serializable;

public class Order implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.orderNo
     *
     * @mbggenerated
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.deliveryman
     *
     * @mbggenerated
     */
    private Integer deliveryman;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.remakr
     *
     * @mbggenerated
     */
    private String remakr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.createTime
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_order.updateTime
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_order
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.id
     *
     * @return the value of t_order.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.id
     *
     * @param id the value for t_order.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.userId
     *
     * @return the value of t_order.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.userId
     *
     * @param userId the value for t_order.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.orderNo
     *
     * @return the value of t_order.orderNo
     *
     * @mbggenerated
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.orderNo
     *
     * @param orderNo the value for t_order.orderNo
     *
     * @mbggenerated
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.status
     *
     * @return the value of t_order.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.status
     *
     * @param status the value for t_order.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.deliveryman
     *
     * @return the value of t_order.deliveryman
     *
     * @mbggenerated
     */
    public Integer getDeliveryman() {
        return deliveryman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.deliveryman
     *
     * @param deliveryman the value for t_order.deliveryman
     *
     * @mbggenerated
     */
    public void setDeliveryman(Integer deliveryman) {
        this.deliveryman = deliveryman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.remakr
     *
     * @return the value of t_order.remakr
     *
     * @mbggenerated
     */
    public String getRemakr() {
        return remakr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.remakr
     *
     * @param remakr the value for t_order.remakr
     *
     * @mbggenerated
     */
    public void setRemakr(String remakr) {
        this.remakr = remakr == null ? null : remakr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.createTime
     *
     * @return the value of t_order.createTime
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.createTime
     *
     * @param createTime the value for t_order.createTime
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_order.updateTime
     *
     * @return the value of t_order.updateTime
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_order.updateTime
     *
     * @param updateTime the value for t_order.updateTime
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}