package com.linfeiyang.shop.mybatis.mapper;

import com.linfeiyang.shop.mybatis.model.Order;
import org.apache.ibatis.annotations.*;

import java.util.List;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_order (id, userId, ",
        "orderNo, `status`, ",
        "deliveryman, remakr, ",
        "createTime, updateTime)",
        "values (#{id,jdbcType=INTEGER}, #{userId,jdbcType=INTEGER}, ",
        "#{orderNo,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{deliveryman,jdbcType=INTEGER}, #{remakr,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=INTEGER}, #{updateTime,jdbcType=INTEGER})"
    })
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, userId, orderNo, `status`, deliveryman, remakr, createTime, updateTime",
        "from t_order",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("BaseResultMap")
    Order selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order
     *
     * @mbggenerated
     */
    @Update({
        "update t_order",
        "set userId = #{userId,jdbcType=INTEGER},",
          "orderNo = #{orderNo,jdbcType=VARCHAR},",
          "`status` = #{status,jdbcType=INTEGER},",
          "deliveryman = #{deliveryman,jdbcType=INTEGER},",
          "remakr = #{remakr,jdbcType=VARCHAR},",
          "createTime = #{createTime,jdbcType=INTEGER},",
          "updateTime = #{updateTime,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Order record);

    @Select("select * from t_order order by id desc limit #{start,jdbcType=INTEGER},#{size,jdbcType=INTEGER}")
    List<Order> selectOrders(@Param("start") Integer start, @Param("size") Integer size);
}