package com.linfeiyang.shop.mybatis.mapper;

import com.linfeiyang.shop.mybatis.model.OrderDetail;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface OrderDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_order_detail (id, orderId, ",
        "productId, `standard`, ",
        "price, totalPrice, ",
        "`sum`, unit, barCode, ",
        "discount, `name`, ",
        "shortDescribe, remark, ",
        "`describe`)",
        "values (#{id,jdbcType=INTEGER}, #{orderId,jdbcType=INTEGER}, ",
        "#{productId,jdbcType=INTEGER}, #{standard,jdbcType=VARCHAR}, ",
        "#{price,jdbcType=DECIMAL}, #{totalPrice,jdbcType=DECIMAL}, ",
        "#{sum,jdbcType=INTEGER}, #{unit,jdbcType=VARCHAR}, #{barCode,jdbcType=VARCHAR}, ",
        "#{discount,jdbcType=DECIMAL}, #{name,jdbcType=VARCHAR}, ",
        "#{shortDescribe,jdbcType=VARCHAR}, #{remark,jdbcType=VARCHAR}, ",
        "#{describe,jdbcType=LONGVARCHAR})"
    })
    int insert(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated
     */
    int insertSelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, orderId, productId, `standard`, price, totalPrice, `sum`, unit, barCode, ",
        "discount, `name`, shortDescribe, remark, `describe`",
        "from t_order_detail",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("ResultMapWithBLOBs")
    OrderDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated
     */
    @Update({
        "update t_order_detail",
        "set orderId = #{orderId,jdbcType=INTEGER},",
          "productId = #{productId,jdbcType=INTEGER},",
          "`standard` = #{standard,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "totalPrice = #{totalPrice,jdbcType=DECIMAL},",
          "`sum` = #{sum,jdbcType=INTEGER},",
          "unit = #{unit,jdbcType=VARCHAR},",
          "barCode = #{barCode,jdbcType=VARCHAR},",
          "discount = #{discount,jdbcType=DECIMAL},",
          "`name` = #{name,jdbcType=VARCHAR},",
          "shortDescribe = #{shortDescribe,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR},",
          "`describe` = #{describe,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(OrderDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_order_detail
     *
     * @mbggenerated
     */
    @Update({
        "update t_order_detail",
        "set orderId = #{orderId,jdbcType=INTEGER},",
          "productId = #{productId,jdbcType=INTEGER},",
          "`standard` = #{standard,jdbcType=VARCHAR},",
          "price = #{price,jdbcType=DECIMAL},",
          "totalPrice = #{totalPrice,jdbcType=DECIMAL},",
          "`sum` = #{sum,jdbcType=INTEGER},",
          "unit = #{unit,jdbcType=VARCHAR},",
          "barCode = #{barCode,jdbcType=VARCHAR},",
          "discount = #{discount,jdbcType=DECIMAL},",
          "`name` = #{name,jdbcType=VARCHAR},",
          "shortDescribe = #{shortDescribe,jdbcType=VARCHAR},",
          "remark = #{remark,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(OrderDetail record);
}