package com.linfeiyang.shop.mybatis.mapper;

import com.linfeiyang.shop.mybatis.model.Product;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.ResultMap;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

public interface ProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated
     */
    @Insert({
        "insert into t_product (id, `name`, ",
        "shortDescribe, image, ",
        "inventory, price, ",
        "unit, barCode, `standard`, ",
        "discount, createTime, ",
        "updateTime, `describe`)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{shortDescribe,jdbcType=VARCHAR}, #{image,jdbcType=VARCHAR}, ",
        "#{inventory,jdbcType=INTEGER}, #{price,jdbcType=DECIMAL}, ",
        "#{unit,jdbcType=VARCHAR}, #{barCode,jdbcType=VARCHAR}, #{standard,jdbcType=VARCHAR}, ",
        "#{discount,jdbcType=DECIMAL}, #{createTime,jdbcType=INTEGER}, ",
        "#{updateTime,jdbcType=INTEGER}, #{describe,jdbcType=LONGVARCHAR})"
    })
    int insert(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated
     */
    int insertSelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "id, `name`, shortDescribe, image, inventory, price, unit, barCode, `standard`, ",
        "discount, createTime, updateTime, `describe`",
        "from t_product",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @ResultMap("ResultMapWithBLOBs")
    Product selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated
     */
    @Update({
        "update t_product",
        "set `name` = #{name,jdbcType=VARCHAR},",
          "shortDescribe = #{shortDescribe,jdbcType=VARCHAR},",
          "image = #{image,jdbcType=VARCHAR},",
          "inventory = #{inventory,jdbcType=INTEGER},",
          "price = #{price,jdbcType=DECIMAL},",
          "unit = #{unit,jdbcType=VARCHAR},",
          "barCode = #{barCode,jdbcType=VARCHAR},",
          "`standard` = #{standard,jdbcType=VARCHAR},",
          "discount = #{discount,jdbcType=DECIMAL},",
          "createTime = #{createTime,jdbcType=INTEGER},",
          "updateTime = #{updateTime,jdbcType=INTEGER},",
          "`describe` = #{describe,jdbcType=LONGVARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKeyWithBLOBs(Product record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_product
     *
     * @mbggenerated
     */
    @Update({
        "update t_product",
        "set `name` = #{name,jdbcType=VARCHAR},",
          "shortDescribe = #{shortDescribe,jdbcType=VARCHAR},",
          "image = #{image,jdbcType=VARCHAR},",
          "inventory = #{inventory,jdbcType=INTEGER},",
          "price = #{price,jdbcType=DECIMAL},",
          "unit = #{unit,jdbcType=VARCHAR},",
          "barCode = #{barCode,jdbcType=VARCHAR},",
          "`standard` = #{standard,jdbcType=VARCHAR},",
          "discount = #{discount,jdbcType=DECIMAL},",
          "createTime = #{createTime,jdbcType=INTEGER},",
          "updateTime = #{updateTime,jdbcType=INTEGER}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Product record);
}